name: iampoor
description: A new Flutter application called I am Poor application to solidfy the concepts we have learned last week. <a href="https://www.vecteezy.com/free-vector/rock">Rock Vectors by Vecteezy</a>

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/